FIRST_LIST_X_START = 10
FIRST_LIST_Y_START = 70
FIRST_LIST_WIDTH = 300
FIRST_LIST_HEIGHT = 250
FIRST_LIST_X_END = FIRST_LIST_X_START + FIRST_LIST_WIDTH
FIRST_LIST_Y_END = FIRST_LIST_Y_START + FIRST_LIST_HEIGHT

ADD_BUTTON_X_START = FIRST_LIST_X_END + 10
ADD_BUTTON_Y_START = FIRST_LIST_Y_START + 10
ADD_BUTTON_WIDTH = 50
ADD_BUTTON_HEIGHT = 50
ADD_BUTTON_X_END = ADD_BUTTON_X_START + ADD_BUTTON_WIDTH
ADD_BUTTON_Y_END = ADD_BUTTON_Y_START + ADD_BUTTON_HEIGHT

INSERT_BUTTON_X_START = FIRST_LIST_X_END + 10
INSERT_BUTTON_Y_START = ADD_BUTTON_Y_END + 5
INSERT_BUTTON_WIDTH = 50
INSERT_BUTTON_HEIGHT = 50
INSERT_BUTTON_X_END = INSERT_BUTTON_X_START + INSERT_BUTTON_WIDTH
INSERT_BUTTON_Y_END = INSERT_BUTTON_Y_START + INSERT_BUTTON_HEIGHT

DELETE_BUTTON_X_START = FIRST_LIST_X_END + 10
DELETE_BUTTON_Y_START = INSERT_BUTTON_Y_END + 5
DELETE_BUTTON_WIDTH = 50
DELETE_BUTTON_HEIGHT = 50
DELETE_BUTTON_X_END = DELETE_BUTTON_X_START + DELETE_BUTTON_WIDTH
DELETE_BUTTON_Y_END = DELETE_BUTTON_Y_START + DELETE_BUTTON_HEIGHT

SECOND_LIST_X_START = DELETE_BUTTON_X_END + 10
SECOND_LIST_Y_START = FIRST_LIST_Y_START
SECOND_LIST_WIDTH = 300
SECOND_LIST_HEIGHT = 250
SECOND_LIST_X_END = SECOND_LIST_X_START + SECOND_LIST_WIDTH
SECOND_LIST_Y_END = SECOND_LIST_Y_START + SECOND_LIST_HEIGHT

THIRD_LIST_X_START = SECOND_LIST_X_END + 15
THIRD_LIST_Y_START = FIRST_LIST_Y_START
THIRD_LIST_WIDTH = 150
THIRD_LIST_HEIGHT = 250
THIRD_LIST_X_END = THIRD_LIST_X_START + THIRD_LIST_WIDTH
THIRD_LIST_Y_END = THIRD_LIST_Y_START + THIRD_LIST_HEIGHT

FOURTH_LIST_X_START = THIRD_LIST_X_END + 15
FOURTH_LIST_Y_START = FIRST_LIST_Y_START
FOURTH_LIST_WIDTH = 150
FOURTH_LIST_HEIGHT = 250
FOURTH_LIST_X_END = FOURTH_LIST_X_START + FOURTH_LIST_WIDTH
FOURTH_LIST_Y_END = FOURTH_LIST_Y_START + FOURTH_LIST_HEIGHT

FIFTH_LIST_X_START = FOURTH_LIST_X_END + 15
FIFTH_LIST_Y_START = FIRST_LIST_Y_START
FIFTH_LIST_WIDTH = 150
FIFTH_LIST_HEIGHT = 250
FIFTH_LIST_X_END = FIFTH_LIST_X_START + FIFTH_LIST_WIDTH
FIFTH_LIST_Y_END = FIFTH_LIST_Y_START + FIFTH_LIST_HEIGHT

SIXTH_LIST_X_START = FIFTH_LIST_X_END + 15
SIXTH_LIST_Y_START = FIRST_LIST_Y_START
SIXTH_LIST_WIDTH = 150
SIXTH_LIST_HEIGHT = 250
SIXTH_LIST_X_END = SIXTH_LIST_X_START + SIXTH_LIST_WIDTH
SIXTH_LIST_Y_END = SIXTH_LIST_Y_START + SIXTH_LIST_HEIGHT

POINT_AXIS_X_START = THIRD_LIST_X_START
POINT_AXIS_Y_START = THIRD_LIST_Y_END + 5
POINT_AXIS_WIDTH = 70
POINT_AXIS_HEIGHT = 30
POINT_AXIS_X_END = POINT_AXIS_X_START + POINT_AXIS_WIDTH
POINT_AXIS_Y_END = POINT_AXIS_Y_START + POINT_AXIS_HEIGHT

SET_IMAGE_X_START = THIRD_LIST_X_START
SET_IMAGE_Y_START = POINT_AXIS_Y_END + 5
SET_IMAGE_WIDTH = 110
SET_IMAGE_HEIGHT = 30
SET_IMAGE_X_END = SET_IMAGE_X_START + SET_IMAGE_WIDTH
SET_IMAGE_Y_END = SET_IMAGE_Y_START + SET_IMAGE_HEIGHT

SET_RELATIVE_DIST_X_START = THIRD_LIST_X_START
SET_RELATIVE_DIST_Y_START = SET_IMAGE_Y_END + 5
SET_RELATIVE_DIST_WIDTH = 180
SET_RELATIVE_DIST_HEIGHT = 30
SET_RELATIVE_DIST_X_END = SET_RELATIVE_DIST_X_START + SET_RELATIVE_DIST_WIDTH
SET_RELATIVE_DIST_Y_END = SET_RELATIVE_DIST_Y_START + SET_RELATIVE_DIST_HEIGHT 

SET_EXCEL_FILE_X_START = SET_IMAGE_X_END + 3
SET_EXCEL_FILE_Y_START = FOURTH_LIST_Y_END + 5
SET_EXCEL_FILE_WIDTH = 50
SET_EXCEL_FILE_HEIGHT = 30
SET_EXCEL_FILE_X_END = SET_EXCEL_FILE_X_START + SET_EXCEL_FILE_WIDTH
SET_EXCEL_FILE_Y_END = SET_EXCEL_FILE_Y_START + SET_EXCEL_FILE_HEIGHT

SET_KEYPRESS_X_START = FOURTH_LIST_X_START
SET_KEYPRESS_Y_START = THIRD_LIST_Y_END + 5
SET_KEYPRESS_WIDTH = 100
SET_KEYPRESS_HEIGHT = 30
SET_KEYPRESS_X_END = SET_KEYPRESS_X_START + SET_KEYPRESS_WIDTH
SET_KEYPRESS_Y_END = SET_KEYPRESS_Y_START + SET_KEYPRESS_HEIGHT

KEYPRESS_APPLY_BUTTON_X_START = SET_KEYPRESS_X_END + 3
KEYPRESS_APPLY_BUTTON_Y_START = THIRD_LIST_Y_END + 5
KEYPRESS_APPLY_BUTTON_WIDTH = 50
KEYPRESS_APPLY_BUTTON_HEIGHT = 30
KEYPRESS_APPLY_BUTTON_X_END = KEYPRESS_APPLY_BUTTON_X_START + KEYPRESS_APPLY_BUTTON_WIDTH
KEYPRESS_APPLY_BUTTON_Y_END = KEYPRESS_APPLY_BUTTON_Y_START + KEYPRESS_APPLY_BUTTON_HEIGHT

SET_INTERVAL_X_START = FIFTH_LIST_X_START
SET_INTERVAL_Y_START = KEYPRESS_APPLY_BUTTON_Y_START
SET_INTERVAL_WIDTH = 100
SET_INTERVAL_HEIGHT = 30
SET_INTERVAL_X_END = SET_INTERVAL_X_START + SET_INTERVAL_WIDTH
SET_INTERVAL_Y_END = SET_INTERVAL_Y_START + SET_INTERVAL_HEIGHT

INTERVAL_APPLY_BUTTON_X_START = SET_INTERVAL_X_END + 3
INTERVAL_APPLY_BUTTON_Y_START = KEYPRESS_APPLY_BUTTON_Y_START
INTERVAL_APPLY_BUTTON_WIDTH = 50
INTERVAL_APPLY_BUTTON_HEIGHT = 30
INTERVAL_APPLY_BUTTON_X_END = INTERVAL_APPLY_BUTTON_X_START + INTERVAL_APPLY_BUTTON_WIDTH
INTERVAL_APPLY_BUTTON_Y_END = INTERVAL_APPLY_BUTTON_Y_START + INTERVAL_APPLY_BUTTON_HEIGHT

SET_NEXT_STEP_X_START = SIXTH_LIST_X_START
SET_NEXT_STEP_Y_START = KEYPRESS_APPLY_BUTTON_Y_START
SET_NEXT_STEP_WIDTH = 100
SET_NEXT_STEP_HEIGHT = 30
SET_NEXT_STEP_X_END = SET_NEXT_STEP_X_START + SET_NEXT_STEP_WIDTH
SET_NEXT_STEP_Y_END = SET_NEXT_STEP_Y_START + SET_NEXT_STEP_HEIGHT

NEXT_STEP_APPLY_BUTTON_X_START = SET_NEXT_STEP_X_END + 5
NEXT_STEP_APPLY_BUTTON_Y_START = KEYPRESS_APPLY_BUTTON_Y_START
NEXT_STEP_APPLY_BUTTON_WIDTH = 50
NEXT_STEP_APPLY_BUTTON_HEIGHT = 30
NEXT_STEP_APPLY_BUTTON_X_END = NEXT_STEP_APPLY_BUTTON_X_START + NEXT_STEP_APPLY_BUTTON_WIDTH
NEXT_STEP_APPLY_BUTTON_Y_END = NEXT_STEP_APPLY_BUTTON_Y_START + NEXT_STEP_APPLY_BUTTON_HEIGHT

EXECUTE_X_START = SIXTH_LIST_X_END + 15
EXECUTE_Y_START = SIXTH_LIST_Y_START + 5
EXECUTE_WIDTH = 60
EXECUTE_HEIGHT = 60
EXECUTE_X_END = EXECUTE_X_START + EXECUTE_WIDTH
EXECUTE_Y_END = EXECUTE_Y_START + EXECUTE_HEIGHT

SAVE_X_START = SIXTH_LIST_X_END + 15
SAVE_Y_START = EXECUTE_Y_END + 5
SAVE_WIDTH = 60
SAVE_HEIGHT = 60
SAVE_X_END = SAVE_X_START + SAVE_WIDTH
SAVE_Y_END = SAVE_Y_START + SAVE_HEIGHT

ADJUST_AXIS_X_START = SIXTH_LIST_X_END + 15
ADJUST_AXIS_Y_START = SAVE_Y_END + 5
ADJUST_AXIS_WIDTH = 60
ADJUST_AXIS_HEIGHT = 60
ADJUST_AXIS_X_END = ADJUST_AXIS_X_START + ADJUST_AXIS_WIDTH
ADJUST_AXIS_Y_END = ADJUST_AXIS_Y_START + ADJUST_AXIS_HEIGHT

REGISTER_LIST_X_START = 10
REGISTER_LIST_Y_START = 30
REGISTER_LIST_WIDTH = 250
REGISTER_LIST_HEIGHT = 250
REGISTER_LIST_X_END = REGISTER_LIST_X_START + REGISTER_LIST_WIDTH
REGISTER_LIST_Y_END = REGISTER_LIST_Y_START + REGISTER_LIST_HEIGHT

REGISTER_ADD_BUTTON_X_START = REGISTER_LIST_X_END + 10
REGISTER_ADD_BUTTON_Y_START = REGISTER_LIST_Y_START + 10
REGISTER_ADD_BUTTON_WIDTH = 50
REGISTER_ADD_BUTTON_HEIGHT = 50
REGISTER_ADD_BUTTON_X_END = REGISTER_ADD_BUTTON_X_START + REGISTER_ADD_BUTTON_WIDTH
REGISTER_ADD_BUTTON_Y_END = REGISTER_ADD_BUTTON_Y_START + REGISTER_ADD_BUTTON_HEIGHT

REGISTER_DELETE_BUTTON_X_START = REGISTER_LIST_X_END + 10
REGISTER_DELETE_BUTTON_Y_START = REGISTER_ADD_BUTTON_Y_END + 5
REGISTER_DELETE_BUTTON_WIDTH = 50
REGISTER_DELETE_BUTTON_HEIGHT = 50
REGISTER_DELETE_BUTTON_X_END = REGISTER_DELETE_BUTTON_X_START + REGISTER_DELETE_BUTTON_WIDTH
REGISTER_DELETE_BUTTON_Y_END = REGISTER_DELETE_BUTTON_Y_START + REGISTER_DELETE_BUTTON_HEIGHT

REGISTER_SAVE_X_START = REGISTER_LIST_X_END + 10
REGISTER_SAVE_Y_START = REGISTER_DELETE_BUTTON_Y_END + 5
REGISTER_SAVE_WIDTH = 50
REGISTER_SAVE_HEIGHT = 50
REGISTER_SAVE_X_END = REGISTER_SAVE_X_START + REGISTER_SAVE_WIDTH
REGISTER_SAVE_Y_END = REGISTER_SAVE_Y_START + REGISTER_SAVE_HEIGHT

CAPTURED_IMAGE_TOGGLE_X_START = SECOND_LIST_X_START
CAPTURED_IMAGE_TOGGLE_Y_START = SECOND_LIST_Y_END + 10
CAPTURED_IMAGE_TOGGLE_WIDTH = 150
CAPTURED_IMAGE_TOGGLE_HEIGHT = 40
CAPTURED_IMAGE_TOGGLE_X_END = CAPTURED_IMAGE_TOGGLE_X_START + CAPTURED_IMAGE_TOGGLE_WIDTH
CAPTURED_IMAGE_TOGGLE_Y_END = CAPTURED_IMAGE_TOGGLE_Y_START + CAPTURED_IMAGE_TOGGLE_HEIGHT
